### ISSUE TITLE
Forget panics in 0.7.0-rc.0

### ISSUE THREAD

**Issue by tamalsaha** [appscode/stash#373]
From @galexrt in Slack:

It seems that backups work when the Check Job does **not** exist and is then created in the process after the backup. When another backup is triggered in that time (replicas > 1) the whole process seems to panic (for whatever reason) and fail with "Check Job already exists" in the end sometimes 

that is weird it seems to work sometimes.. now after a successful backup and forget I get this error:
```
F0314 15:56:09.074281      47 backup.go:79] [failed to create check job, reason: jobs.batch "stash-check-stash-gitlab" already exists]
goroutine 1 [running]:
github.com/appscode/stash/vendor/github.com/golang/glog.stacks(0xc42016e800, 0xc4204ff600, 0x87, 0x1e6)
    /go/src/github.com/appscode/stash/vendor/github.com/golang/glog/glog.go:766 +0xcf
github.com/appscode/stash/vendor/github.com/golang/glog.(*loggingT).output(0x2532560, 0xc400000003, 0xc42054e210, 0x2378551, 0x9, 0x4f, 0x0)
    /go/src/github.com/appscode/stash/vendor/github.com/golang/glog/glog.go:717 +0x30f
github.com/appscode/stash/vendor/github.com/golang/glog.(*loggingT).printDepth(0x2532560, 0x3, 0x1, 0xc42088dac8, 0x1, 0x1)
    /go/src/github.com/appscode/stash/vendor/github.com/golang/glog/glog.go:646 +0x129
github.com/appscode/stash/vendor/github.com/golang/glog.FatalDepth(0x1, 0xc42088dac8, 0x1, 0x1)
    /go/src/github.com/appscode/stash/vendor/github.com/golang/glog/glog.go:1131 +0x5d
github.com/appscode/stash/vendor/github.com/appscode/go/log.Fatal(0xc4201ba3e0, 0x1, 0x1)
    /go/src/github.com/appscode/stash/vendor/github.com/appscode/go/log/log.go:21 +0x9e
github.com/appscode/stash/pkg/cmds.NewCmdBackup.func1(0xc420540280, 0xc4201647e0, 0x0, 0x7)
    /go/src/github.com/appscode/stash/pkg/cmds/backup.go:79 +0x54d
github.com/appscode/stash/vendor/github.com/spf13/cobra.(*Command).execute(0xc420540280, 0xc420164770, 0x7, 0x7, 0xc420540280, 0xc420164770)
    /go/src/github.com/appscode/stash/vendor/github.com/spf13/cobra/command.go:757 +0x2c1
github.com/appscode/stash/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc4201b8a00, 0xc420540c80, 0xc420540a00, 0xc420540280)
    /go/src/github.com/appscode/stash/vendor/github.com/spf13/cobra/command.go:843 +0x30a
github.com/appscode/stash/vendor/github.com/spf13/cobra.(*Command).Execute(0xc4201b8a00, 0x8, 0x0)
    /go/src/github.com/appscode/stash/vendor/github.com/spf13/cobra/command.go:791 +0x2b
main.main()
    /go/src/github.com/appscode/stash/main.go:23 +0x77
```

The Jobs Pod exist but is hanging with `InvalidImageName` because the given image is just `appscode/stash:` without a tag (edited)

I'll try to check if it works completely when the Job doesn't exist
It seems that the error is actually when it creates the Job. When the Job does not exist it fails with the trace from earlier, if it exists it fails with the error that it exists but doesn't seem to report a failure to the monitoring

**Comment by tamalsaha** [comment]
Find full conversation : https://appscode.slack.com/files/U8LQ66AGY/F9QQC5Y07/-.txt

**Comment by tamalsaha** [comment]
Fixed
