### ISSUE TITLE
Deployed latest helm chart and getting error during sidecar creation

### ISSUE THREAD

**Issue by mitchellmaler** [appscode/stash#556]
I have deployed Stash using Helm and verified it deployed. I then created a Restic CRD to backup PVCs and the sidecars started deploying then they are erroring.

```
Error running command '/bin/restic [snapshots --json --cache-dir /tmp/restic-cache]' output:
[golang-sh]$ /bin/restic snapshots --json --cache-dir /tmp/restic-cache
```

Sidecar
```
I0820 01:25:38.580190       1 logs.go:19] FLAG: --alsologtostderr="false"I0820 01:25:38.580953       1 logs.go:19] FLAG: --burst="100"
I0820 01:25:38.581008       1 logs.go:19] FLAG: --docker-registry="appscode"
I0820 01:25:38.581023       1 logs.go:19] FLAG: --enable-analytics="true"
I0820 01:25:38.581033       1 logs.go:19] FLAG: --enable-rbac="true"
I0820 01:25:38.581042       1 logs.go:19] FLAG: --help="false"
I0820 01:25:38.581051       1 logs.go:19] FLAG: --image-tag="0.7.0"
I0820 01:25:38.581060       1 logs.go:19] FLAG: --kubeconfig=""
I0820 01:25:38.581111       1 logs.go:19] FLAG: --log_backtrace_at=":0"
I0820 01:25:38.581121       1 logs.go:19] FLAG: --log_dir=""
I0820 01:25:38.581131       1 logs.go:19] FLAG: --logtostderr="false"
I0820 01:25:38.581140       1 logs.go:19] FLAG: --master=""
I0820 01:25:38.581171       1 logs.go:19] FLAG: --pushgateway-url="http://stash-operator.stash.svc:56789"
I0820 01:25:38.581187       1 logs.go:19] FLAG: --qps="100"
I0820 01:25:38.581202       1 logs.go:19] FLAG: --restic-name="minio-azure-backup-restic"
I0820 01:25:38.581216       1 logs.go:19] FLAG: --resync-period="5m0s"
I0820 01:25:38.581226       1 logs.go:19] FLAG: --run-via-cron="true"
I0820 01:25:38.581263       1 logs.go:19] FLAG: --scratch-dir="/tmp"
I0820 01:25:38.581277       1 logs.go:19] FLAG: --stderrthreshold="0"
I0820 01:25:38.581287       1 logs.go:19] FLAG: --v="3"
I0820 01:25:38.581296       1 logs.go:19] FLAG: --vmodule=""
I0820 01:25:38.581306       1 logs.go:19] FLAG: --workload-kind="StatefulSet"
I0820 01:25:38.581315       1 logs.go:19] FLAG: --workload-name="minio"
W0820 01:25:38.880706       1 client_config.go:533] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0820 01:25:39.022677       1 backup.go:73] [Running backup periodically via cron]
I0820 01:25:39.052783       1 backup.go:227] Found restic minio-azure-backup-restic
I0820 01:25:39.066316       1 backup.go:235] Found repository secret minio-backup-azure-secret
E0820 01:25:39.066894       1 restic.go:204] Error running command '/bin/restic [snapshots --json --cache-dir /tmp/restic-cache]' output:
[golang-sh]$ /bin/restic snapshots --json --cache-dir /tmp/restic-cache

E0820 01:25:39.067644       1 restic.go:204] Error running command '/bin/restic [init --cache-dir /tmp/restic-cache]' output:
[golang-sh]$ /bin/restic init --cache-dir /tmp/restic-cache

I0820 01:25:39.091446       1 recorder.go:81] [Event created:  minio-azure-backup-restic.154c734b04db7343]
F0820 01:25:39.091498       1 backup.go:75] [failed to setup backup. Error: fork/exec /bin/restic: invalid argument]
goroutine 1 [running]:
github.com/appscode/stash/vendor/github.com/golang/glog.stacks(0xc420404c00, 0xc420286600, 0x75, 0x1e6)
        /go/src/github.com/appscode/stash/vendor/github.com/golang/glog/glog.go:766 +0xcf
github.com/appscode/stash/vendor/github.com/golang/glog.(*loggingT).output(0x4026e20, 0xc400000003, 0xc4202b4c60, 0x3e2f941, 0x9, 0x4b, 0x0)
        /go/src/github.com/appscode/stash/vendor/github.com/golang/glog/glog.go:717 +0x322
github.com/appscode/stash/vendor/github.com/golang/glog.(*loggingT).printDepth(0x4026e20, 0x3, 0x1, 0xc4208c9a40, 0x1, 0x1)
        /go/src/github.com/appscode/stash/vendor/github.com/golang/glog/glog.go:646 +0x12a
github.com/appscode/stash/vendor/github.com/golang/glog.FatalDepth(0x1, 0xc4208c9a40, 0x1, 0x1)
        /go/src/github.com/appscode/stash/vendor/github.com/golang/glog/glog.go:1131 +0x5d
github.com/appscode/stash/vendor/github.com/appscode/go/log.Fatal(0xc42020f2c0, 0x1, 0x1)
        /go/src/github.com/appscode/stash/vendor/github.com/appscode/go/log/log.go:17 +0xa8
github.com/appscode/stash/pkg/cmds.NewCmdBackup.func1(0xc420382500, 0xc420048f70, 0x0, 0xd)
        /go/src/github.com/appscode/stash/pkg/cmds/backup.go:75 +0xb29
github.com/appscode/stash/vendor/github.com/spf13/cobra.(*Command).execute(0xc420382500, 0xc420048dd0, 0xd, 0xd, 0xc420382500, 0xc420048dd0)
        /go/src/github.com/appscode/stash/vendor/github.com/spf13/cobra/command.go:766 +0x2c1
github.com/appscode/stash/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc4205fd680, 0xc420383400, 0xc420383180, 0xc420382500)
        /go/src/github.com/appscode/stash/vendor/github.com/spf13/cobra/command.go:852 +0x334
github.com/appscode/stash/vendor/github.com/spf13/cobra.(*Command).Execute(0xc4205fd680, 0x8, 0x0)
        /go/src/github.com/appscode/stash/vendor/github.com/spf13/cobra/command.go:800 +0x2b
main.main()
        /go/src/github.com/appscode/stash/main.go:23 +0x77
```

Helm Install
```
helm upgrade stash-operator appscode/stash --install
    --version 0.7.0
    --namespace stash
    --set apiserver.ca="[CA String]"
    --set apiserver.enableValidatingWebhook=true
    --set apiserver.enableMutatingWebhook=true
    --set rbac.create=true
```

Azure Backup Restic File
```yaml
apiVersion: stash.appscode.com/v1alpha1
kind: Restic
metadata:
  name: minio-azure-backup-restic
spec:
  selector:
    matchLabels:
      app: minio
  fileGroups:
  - path: /data
    retentionPolicyName: 'keep-last-5'
  backend:
    azure:
      container: minio
      prefix: corp
    storageSecretName: backup-azure-secret
  schedule: '@every 1m'
  volumeMounts:
  - mountPath: /data
    name: data
  retentionPolicies:
  - name: 'keep-last-5'
    keepLast: 5
    prune: true
```

The secrete has all three
RESTIC_PASSWORD
AZURE_ACCOUNT_NAME
AZURE_ACCOUNT_KEY

When I describe the restic crd it has these error
```
Warning  SetupFailed  4m    stash-backup  failed to setup backup. Error: fork/exec /bin/restic: invalid argument
```

**Comment by tamalsaha** [comment]
What is your `kubectl version` ?

Also, can you tell us a bit about your setup? Are you backing up Minio server etc? It seems like something is not correct in the CRD.

```
E0820 01:25:39.066894       1 restic.go:204] Error running command '/bin/restic [snapshots --json --cache-dir /tmp/restic-cache]' output:
[golang-sh]$ /bin/restic snapshots --json --cache-dir /tmp/restic-cache

E0820 01:25:39.067644       1 restic.go:204] Error running command '/bin/restic [init --cache-dir /tmp/restic-cache]' output:
[golang-sh]$ /bin/restic init --cache-dir /tmp/restic-cache

I0820 01:25:39.091446       1 recorder.go:81] [Event created:  minio-azure-backup-restic.154c734b04db7343]
F0820 01:25:39.091498       1 backup.go:75] [failed to setup backup. Error: fork/exec /bin/restic: invalid argument]

```

**Comment by mitchellmaler** [comment]
@tamalsaha @hossainemruz Yes I have Minio distributed deployed as a stateful set with the volume data mounted at /data. I am trying to back that up to Azure blob storage. 

Kubernetes Version: 
```
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:34:22Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

Yea I am trying to figure out what is the issue in the CRD. The error message just says 'Error running command' but nothing pointing to what was the error or bad config.

**Comment by tamalsaha** [comment]
It is trying to run the following commands:

```
[golang-sh]$ /bin/restic snapshots --json --cache-dir /tmp/restic-cache
[golang-sh]$ /bin/restic init --cache-dir /tmp/restic-cache
```

Credentials are passed using ENV variable like here: https://github.com/appscode/stash/blob/master/pkg/cli/env.go#L109

**Comment by mitchellmaler** [comment]
@tamalsaha Yea I have the secret referenced and three variable set.

```
apiVersion: v1
kind: Secret
metadata:
  name: backup-azure-secret
  labels:
    app: minio
data:
  RESTIC_PASSWORD: [data]
  AZURE_ACCOUNT_NAME: [data]
  AZURE_ACCOUNT_KEY: [data]
```

Can it give more logging about why those commands failed? Like is it missing a config variable or is one malformed/incorrect. With it just saying failed doesn't give me much to troubleshoot. I copied the example azure restic crd from the documentation for this so I didn't do much customization except for the volume location.

**Comment by tamalsaha** [comment]
There is no way to get any more logs here. But you can exec into the sidecar and run these commands yourself.

```
$ kubectl exec -it -n <ns> <pod-name> -c stash sh

# inside pod
export RESTIC_PASSWORD=<data>
export AZURE_ACCOUNT_NAME=<data>
export AZURE_ACCOUNT_KEY-<data>
/bin/restic init --cache-dir /tmp/restic-cache
```

**Comment by mitchellmaler** [comment]
@tamalsaha I can't exec into the container because it fails to startup.

**Comment by mitchellmaler** [comment]
I just checked the logs again and now I am getting a different message. 
```
Fatal: unable to open repo at azure:minio:/corp/statefulset/minio-3: NewBasicClient: azure: account name is not valid: it must be between 3 and 24 characters, and only may contain numbers and lowercase letters: ctscernerdevtools
```

That is a better error message :)

**Comment by tamalsaha** [comment]
You can just download the restic cli from their project https://github.com/restic/restic/releases/tag/v0.8.3 . Then run these commands from yur workstation.

One common mistake is that the credentials in secrets have trailing `\n`. Please double check that you don't have that.

**Comment by mitchellmaler** [comment]
@tamalsaha That was my issue, dang it! Not the first time I have had this issue lol
Thanks!
