### ISSUE TITLE
Stash chart is throwing error

### ISSUE THREAD

**Issue by tamalsaha** [appscode/stash#627]
```
I1208 01:15:06.192340       1 repository.go:58] Sync/Add/Update for Repository default/test-repository-for-webhook-xray
I1208 01:15:06.192362       1 deployment.go:78] Sync/Add/Update for Deployment kube-system/tiller-deploy
E1208 01:15:06.192431       1 worker.go:76] Failed to process key default/test-repository-for-webhook-xray. Reason: stat /tmp/test: no such file or directory
I1208 01:15:06.192717       1 worker.go:80] Error syncing key default/test-repository-for-webhook-xray: stat /tmp/test: no such file or directory
I1208 01:15:06.192840       1 replicasets.go:78] Sync/Add/Update for ReplicaSet kube-system/coredns-78fcdf6894
I1208 01:15:06.193053       1 deployment.go:78] Sync/Add/Update for Deployment kube-system/stash-operator
I1208 01:15:06.193175       1 deployment.go:78] Sync/Add/Update for Deployment kube-system/coredns
I1208 01:15:06.193329       1 deployment.go:78] Sync/Add/Update for Deployment kube-system/kubernetes-dashboard
I1208 01:15:06.193336       1 replicasets.go:78] Sync/Add/Update for ReplicaSet kube-system/coredns-99b9bb8bd
I1208 01:15:06.193381       1 daemonsets.go:69] Sync/Add/Update for DaemonSet kube-system/kube-proxy
I1208 01:15:06.198776       1 repository.go:58] Sync/Add/Update for Repository default/test-repository-for-webhook-xray
E1208 01:15:06.198831       1 worker.go:76] Failed to process key default/test-repository-for-webhook-xray. Reason: stat /tmp/test: no such file or directory
I1208 01:15:06.198843       1 worker.go:80] Error syncing key default/test-repository-for-webhook-xray: stat /tmp/test: no such file or directory
I1208 01:15:06.202379       1 replicasets.go:78] Sync/Add/Update for ReplicaSet kube-system/kubernetes-dashboard-7db4dc666b
I1208 01:15:06.205903       1 replicasets.go:78] Sync/Add/Update for ReplicaSet kube-system/tiller-deploy-57f988f854
I1208 01:15:06.208272       1 replicasets.go:78] Sync/Add/Update for ReplicaSet kube-system/stash-operator-f44858b4b
I1208 01:15:06.209360       1 repository.go:58] Sync/Add/Update for Repository default/test-repository-for-webhook-xray
E1208 01:15:06.209403       1 worker.go:76] Failed to process key default/test-repository-for-webhook-xray. Reason: stat /tmp/test: no such file or directory
I1208 01:15:06.209515       1 worker.go:80] Error syncing key default/test-repository-for-webhook-xray: stat /tmp/test: no such file or directory
I1208 01:15:06.229845       1 repository.go:58] Sync/Add/Update for Repository default/test-repository-for-webhook-xray
E1208 01:15:06.229914       1 worker.go:76] Failed to process key default/test-repository-for-webhook-xray. Reason: stat /tmp/test: no such file or directory
I1208 01:15:06.229929       1 worker.go:80] Error syncing key default/test-repository-for-webhook-xray: stat /tmp/test: no such file or directory
I1208 01:15:06.271245       1 repository.go:58] Sync/Add/Update for Repository default/test-repository-for-webhook-xray
E1208 01:15:06.271624       1 worker.go:76] Failed to process key default/test-repository-for-webhook-xray. Reason: stat /tmp/test: no such file or directory
I1208 01:15:06.271686       1 worker.go:80] Error syncing key default/test-repository-for-webhook-xray: stat /tmp/test: no such file or directory
I1208 01:15:06.355701       1 repository.go:58] Sync/Add/Update for Repository default/test-repository-for-webhook-xray
E1208 01:15:06.355767       1 worker.go:76] Failed to process key default/test-repository-for-webhook-xray. Reason: stat /tmp/test: no such file or directory
E1208 01:15:06.355784       1 worker.go:90] stat /tmp/test: no such file or directory
I1208 01:15:06.355791       1 worker.go:91] Dropping key "default/test-repository-for-webhook-xray" out of the queue: stat /tmp/test: no such file or directory
I1208 01:15:09.863891       1 deployment.go:78] Sync/Add/Update for Deployment kube-system/stash-operator
I1208 01:15:09.866543       1 replicasets.go:78] Sync/Add/Update for ReplicaSet kube-system/stash-operator-f44858b4b
I1208 01:15:10.941414       1 xray.go:221] testing ValidatingWebhook using an object with GVR = stash.appscode.com/v1alpha1, Resource=repositories
W1208 01:15:10.951344       1 xray.go:147] Attempt 1 to detect ValidatingWebhook activation failed due to object is being deleted: repositories.stash.appscode.com "test-repository-for-webhook-xray" already exists
I1208 01:15:10.967053       1 recorder.go:82] Event created: stash-operator.156e368f36bde1e4
panic: object is being deleted: repositories.stash.appscode.com "test-repository-for-webhook-xray" already exists

goroutine 280 [running]:
github.com/appscode/stash/pkg/server.completedConfig.New.func2.1(0xc00064e240, 0xc00044e200, 0xc0006368c0, 0xc00026c3c0)
	/go/src/github.com/appscode/stash/pkg/server/server.go:227 +0x6a6
created by github.com/appscode/stash/pkg/server.completedConfig.New.func2
	/go/src/github.com/appscode/stash/pkg/server/server.go:188 +0x5b



----------------

LAST SEEN   FIRST SEEN   COUNT   NAME                                                     KIND         SUBOBJECT                                  TYPE      REASON                         SOURCE                    MESSAGE
8m          8m           1       stash-operator-f44858b4b-mcdtp.156e365768d2c818          Pod          spec.containers{pushgateway}               Normal    Pulled                         kubelet, minikube         Successfully pulled image "prom/pushgateway:v0.5.2"
8m          8m           1       stash-operator-f44858b4b-mcdtp.156e36599edfd082          Pod          spec.containers{operator}                  Warning   Unhealthy                      kubelet, minikube         Readiness probe failed: Get https://172.17.0.3:8443/healthz: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
7m          7m           1       stash-operator.156e365c05dcf478                          Deployment                                              Warning   AdmissionWebhookNotActivated   stash-operator            Admission webhooks are not activated. Enable it by configuring --enable-admission-plugins flag of kube-apiserver. For details, visit: https://appsco.de/kube-apiserver-webhooks
7m          7m           1       stash-operator.156e365e52e58c35                          Deployment                                              Warning   AdmissionWebhookNotActivated   stash-operator            Admission webhooks are not activated. Enable it by configuring --enable-admission-plugins flag of kube-apiserver. For details, visit: https://appsco.de/kube-apiserver-webhooks
7m          7m           1       stash-operator.156e3662fe238071                          Deployment                                              Warning   AdmissionWebhookNotActivated   stash-operator            Admission webhooks are not activated. Enable it by configuring --enable-admission-plugins flag of kube-apiserver. For details, visit: https://appsco.de/kube-apiserver-webhooks
6m          8m           4       stash-operator-f44858b4b-mcdtp.156e365632d56e6e          Pod          spec.containers{operator}                  Normal    Created                        kubelet, minikube         Created container
6m          8m           4       stash-operator-f44858b4b-mcdtp.156e365641cb843e          Pod          spec.containers{operator}                  Normal    Started                        kubelet, minikube         Started container
6m          6m           1       stash-operator.156e366c4c83fb00                          Deployment                                              Warning   AdmissionWebhookNotActivated   stash-operator            object is being deleted: repositories.stash.appscode.com "test-repository-for-webhook-xray" already exists
6m          7m           4       stash-operator-f44858b4b-mcdtp.156e365c56a960f5          Pod          spec.containers{operator}                  Normal    Pulled                         kubelet, minikube         Container image "appscode/stash:0.8.0" already present on machine
5m          5m           1       stash-operator.156e3677f1322a79                          Deployment                                              Warning   AdmissionWebhookNotActivated   stash-operator            object is being deleted: repositories.stash.appscode.com "test-repository-for-webhook-xray" already exists
4m          4m           1       stash-operator.156e368f36bde1e4                          Deployment                                              Warning   AdmissionWebhookNotActivated   stash-operator            object is being deleted: repositories.stash.appscode.com "test-repository-for-webhook-xray" already exists
3m          7m           18      stash-operator-f44858b4b-mcdtp.156e365e7d2771e8          Pod          spec.containers{operator}                  Warning   BackOff                        kubelet, minikube         Back-off restarting failed container
1m          1m           1       stash-operator.156e36b6cb902cb8                          Deployment                                              Warning   AdmissionWebhookNotActivated   stash-operator            object is being deleted: repositories.stash.appscode.com "test-repository-for-webhook-xray" already exists

```

**Comment by tamalsaha** [comment]
@dNetGuru, please try 0.8.1 . This issue should be fixed.

**Comment by dNetGuru** [comment]
Thanks, I can confirm that `0.8.1` fixes this problem.

**Comment by davidmkrtchian** [comment]
@tamalsaha getting the same problem with V0.33.
Installing Stash with Helm chart (v2024.2.13) and getting the warning message 
Admission webhooks are not activated. Enable it by configuring --enable-admission-plugins flag of kube-apiserver. For details, visit: https://appsco.de/kube-apiserver-webhooks
But I have enabled the ValidatingAdmissionWebhook,MutatingAdmissionWebhook.
If you could provide assistance in resolving this problem, I would greatly appreciate it.
